function [ys_, params, info] = steadystate(ys_, exo_, params)
% Steady state generated by Dynare preprocessor
    info = 0;
    ys_(1)=log(params(9));
    ys_(2)=log(params(10));
    ys_(3)=log(params(11));
    ys_(4)=log(params(12));
    ys_(5)=log(params(13));
    % Auxiliary equations
end
